### PR TITLE
Fix whitespace for Make 4.3

### PR DESCRIPTION
**Pull request by freshe4qa**

### CODE REVIEW

**Comment by larry0x** [comment]
Aren't these two the same thing?

```makefile
whitespace := $(whitespace) $(whitespace)
```

and

```makefile
whitespace += $(whitespace)
```

For reference, the current code was copied from Osmosis: https://github.com/osmosis-labs/osmosis/blob/v14.0.0/Makefile#L52-L55

**Comment by freshe4qa** [comment]
Make 4.3 will only add a space when += is used if the variable it is used on exists. Using += on a non-existing variable would previously create a variable starting with a space.

**Comment by larry0x** [comment]
Yep, I have verified, this problem exists:

```plain
// with whitespace += $(whitespace)
"github.com/cosmos/cosmos-sdk/version.BuildTags=netgo ledger," 

// with whitespace := $(whitespace) $(whitespace)
"github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger"
```

Thanks for the contribution!

**Comment by freshe4qa** [comment]
Always glad to help

**Pull request merged**
