### PR TITLE
Add Dockerfile 

### PR DESCRIPTION
**Pull request by niccoloraspa**
This PR adds a `Dockerfile` and some new commands to the Makefile that allow building a Docker image for Mars.

The Dockerfile is divided in two stages:

1) Builds the `marsd` binary creating a statically link binary with libwasmvm

2) Serves the binary in various runner images, based on the specified `RUNNER_IMAGE` base image.

The Makefile includes the following new commands for building the Docker image:

- `docker-build` - builds the Docker image using the default distroless base image
- `docker-build-distroless` - builds the Docker image using the default distroless base image
- `docker-build-alpine` - builds the Docker image using the Alpine base image
- `docker-build-nonroot` - builds the Docker image using the non-root distroless base image

This is the same docker process we use in Osmosis.

I have used this image to build:

- `osmolabs/mars:1.0.0-rc7`
- `osmolabs/mars:1.0.0`

### CODE REVIEW

**Comment by niccoloraspa** [comment]
By merging this you could also get almost for free:

1) A GitHub action to push images to your Docker registry on every new tag https://github.com/osmosis-labs/osmosis/blob/main/.github/workflows/push-docker-images.yml 

2) A Docker builder that creates a statically linked `marsd` binary: https://github.com/osmosis-labs/osmosis/blob/main/Makefile#L107-L145 so that you could attach them to the "Assets" on a release https://github.com/mars-protocol/hub/releases/tag/v1.0.0 

3) LocalMars https://github.com/osmosis-labs/osmosis/tree/main/tests/localosmosis 

Let me know if I can help!

**Comment by larry0x** [comment]
@niccoloraspa Thanks for the contribution!

Comparing with [Osmosis' Dockerfile](https://github.com/osmosis-labs/osmosis/blob/main/Dockerfile), they have these extra lines:

```dockerfile
EXPOSE 26656
EXPOSE 26657
EXPOSE 1317
```

Are these necessary? (I'm not a docker user so not familiar with this)

> A GitHub action to push images to your Docker registry on every new tag

Let me ask my colleagues to set up an account at Docker registry.

> A Docker builder that creates a statically linked marsd binary both for linux/amd64 and linux/arm64 that you could attach to the release "Assets"

This sounds useful. Can you please do this?

> LocalMars

This is not very useful. Since we do not plan to deploy complex smart contracts on Mars Hub, we do not need a complex testing tool such as LocalMars.

**Comment by larry0x** [comment]
Merging this for now

**Comment by niccoloraspa** [comment]
Awesome! The changes look good

**Pull request merged**
